package commons.game.events;

public enum EventType {
	PLAYER_SEATED,
	PLAYER_LEFT,
	PLAYER_JOINED,
	HAND_STARTED,
	HOLE_CARDS_DEALED,
	BOARD_CARDS_DEALED,
	BETTING_ROUND_STARTED,
	NEXT_PLAYER_TURN,
	BETTING_ROUND_FINISHED,
	SHOWDOWN,
	DECLARE_WINNERS,
	HAND_FINISHED,
	BUY_CHIPS
}
